definitions:
  controller.response:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  title: Test Go API
  version: "1.0"
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Perform a health check.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.response'
        "400":
          description: OK
          schema:
            type: string
        "404":
          description: OK
          schema:
            type: string
        "500":
          description: OK
          schema:
            type: string
      summary: Health check endpoint for application.
      tags:
      - health
swagger: "2.0"
